name: Suptrack CI/CD Pipeline

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Tag for Deployment
        id: set_tag
        run: |
          # Le nom du tag qui a dÃ©clenchÃ© le workflow
          echo "CURRENT_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          SAFE_CURRENT_TAG=$(echo "${GITHUB_REF_NAME}" | tr '.' '_' | tr '[:upper:]' '[:lower:]')
          echo "SAFE_CURRENT_TAG=$SAFE_CURRENT_TAG" >> $GITHUB_ENV
          echo "Tag utilisÃ© pour Docker Compose: $SAFE_CURRENT_TAG"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push Suptrack image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/web:${{  env.SAFE_CURRENT_TAG }}
          echo "ðŸš§ Building $IMAGE"
          docker build --target web -t $IMAGE .
          docker push $IMAGE

      - name: Build and push Celery image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/celery:${{  env.SAFE_CURRENT_TAG }}
          echo "ðŸš§ Building $IMAGE"
          docker build --target web -t $IMAGE .
          docker push $IMAGE

  # --------------------------
  # 2. Deploy to VPS
  # --------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Tag for Deployment
        id: set_tag
        run: |
          # Le nom du tag qui a dÃ©clenchÃ© le workflow
          echo "CURRENT_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          SAFE_CURRENT_TAG=$(echo "${GITHUB_REF_NAME}" | tr '.' '_' | tr '[:upper:]' '[:lower:]')
          echo "SAFE_CURRENT_TAG=$SAFE_CURRENT_TAG" >> $GITHUB_ENV
          echo "Tag utilisÃ© pour Docker Compose: $SAFE_CURRENT_TAG"
      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            echo "ðŸ” Connexion Ã  GHCR"
            echo "${{ secrets.ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "ðŸ“ DÃ©placement dans le rÃ©pertoire du projet"
            cd ${{secrets.VPS_WORKDIR}}

            echo "ðŸ“¥ Mise Ã  jour de la variable TAG [${{env.SAFE_CURRENT_TAG}}] dans le fichier .env"
            # Si TAG existe dÃ©jÃ , on le remplace. Sinon, on l'ajoute.
            if grep -q '^TAG=' .env; then
              sed -i "s/^TAG=.*/TAG=${{env.SAFE_CURRENT_TAG}}/" .env
            else
              echo "TAG=${{env.SAFE_CURRENT_TAG}}" >> .env
            fi
            
            echo "ðŸ“¥ Pull des images depuis GHCR"
            docker compose -f compose.deploy.yml pull

            echo "ðŸš€ DÃ©marrage des services"
            docker compose -f compose.deploy.yml up -d

            echo "ðŸ§¹ Nettoyage des anciens conteneurs..."
            docker system prune -f