services:
  webapp:
    build: 
      context: .
      target: web_image
    entrypoint: [ "sh", "entrypoint.sh" ]
    container_name: webapp-container
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:80
    networks:
      - web_network
      - redis_network
    depends_on:
      webapp_db:
        condition: service_healthy
        restart: true
    env_file: .env

  webapp_db:
    image: postgres:17
    restart: always
    container_name: webapp_db-container
    env_file: .env
    expose:
      - 5432
    networks:
      - web_network
      - db_network
    volumes:
      - ./database/data:/var/lib/postgresql/
    user: "1000:1000"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  celery:
    build:
      context: .
      target: web_image
    command: >
      sh -c "celery -A cosama worker --loglevel=info -E -c 2 &
            celery -A cosama beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
            wait"
    container_name: celery-container
    restart: always
    volumes:
      - .:/app
    depends_on:
      webapp:
        condition: service_started
    networks:
      - web_network
      - redis_network
    env_file: .env

networks:
  web_network:
    name: web_network
  db_network:
    name: db_network
    external: true
  redis_network:
    name: redis_network
    external: true
